// flow-typed signature: 714760223d22f42123819f3a1fd3efba
// flow-typed version: <<STUB>>/buttono_v^0.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buttono'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buttono' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buttono/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buttono/gulpfile.js' {
  declare module.exports: $Exports<'buttono/gulpfile'>;
}
