// flow-typed signature: ea0616e87843aeb4b9944088c0e02504
// flow-typed version: <<STUB>>/gatsby-plugin-google-fonts_v^0.0.4/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-google-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-google-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-google-fonts/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-google-fonts/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-fonts/gatsby-ssr'>;
}
declare module 'gatsby-plugin-google-fonts/index' {
  declare module.exports: $Exports<'gatsby-plugin-google-fonts'>;
}
declare module 'gatsby-plugin-google-fonts/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-fonts'>;
}
