// flow-typed signature: 8110dddcc813da38d16eef63a8ee2951
// flow-typed version: <<STUB>>/gatsby-plugin-purify-css_v^2.2.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-purify-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-purify-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-purify-css/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-purify-css/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-purify-css/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-purify-css/gatsby-node'>;
}
declare module 'gatsby-plugin-purify-css/index' {
  declare module.exports: $Exports<'gatsby-plugin-purify-css'>;
}
declare module 'gatsby-plugin-purify-css/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-purify-css'>;
}
declare module 'gatsby-plugin-purify-css/webpack.config.babel.js' {
  declare module.exports: $Exports<'gatsby-plugin-purify-css/webpack.config.babel'>;
}
