// flow-typed signature: 1256491951e4f105fb5dab58c1abca86
// flow-typed version: <<STUB>>/gatsby_v^1.9.241/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby/__mocks__/fs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/find-page' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/prefetcher' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-browser' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-ssr' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-ssr-docs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/component-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/default-html' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/develop-static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/emitter' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/find-page' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/history' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/prefetcher' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/production-app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/register-service-worker' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/root' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/shallow-differ' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/socketIo' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bin/gatsby' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/get-config-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/load' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/validate' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/log-line-function' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/page-hot-reloader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-css' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-javascript' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/data-explorer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/serve' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-layout-creator/create-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-layout-creator/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-layout-creator/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-layout-creator/validate-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-page-creator/create-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-page-creator/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-page-creator/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/component-page-creator/validate-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/file-parser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/graphql-errors' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/page-query-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/pages-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-compiler' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-queue' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/query-watcher' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/query-runner/redirects-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/joi-schemas/joi' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/add-page-dependency' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/plugin-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/api-to-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/component-data-dependencies' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/components' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/flattened-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/jobs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/last-action' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/layouts' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes-touched' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/program' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/redirects' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/status' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-connection-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-node-connections' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/build-node-types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-key' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-sort-field' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/create-type-name' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/data-tree-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-input-fields-from-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-input-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer-graphql-type' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node-interface' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node-tracking' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/prepare-regex' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/run-sift' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-date' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-browser-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-node-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-runner-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-plugin-extract-graphql' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/cache' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/checkpoints-promise' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/copy-static-directory' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/create-node-id' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-hash-fn' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-ssl-cert' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/hashed-chunk-ids-plugin' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/js-chunk-names' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/source-nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/test-require-error' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-modify-validate' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby/__mocks__/fs.js' {
  declare module.exports: $Exports<'gatsby/__mocks__/fs'>;
}
declare module 'gatsby/cache-dir/__tests__/find-page.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/find-page'>;
}
declare module 'gatsby/cache-dir/__tests__/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/loader'>;
}
declare module 'gatsby/cache-dir/__tests__/prefetcher.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/prefetcher'>;
}
declare module 'gatsby/cache-dir/__tests__/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/strip-prefix'>;
}
declare module 'gatsby/cache-dir/api-runner-browser.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-browser'>;
}
declare module 'gatsby/cache-dir/api-runner-ssr.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-ssr'>;
}
declare module 'gatsby/cache-dir/api-ssr-docs.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-ssr-docs'>;
}
declare module 'gatsby/cache-dir/app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/app'>;
}
declare module 'gatsby/cache-dir/component-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/component-renderer'>;
}
declare module 'gatsby/cache-dir/default-html.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/default-html'>;
}
declare module 'gatsby/cache-dir/develop-static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/develop-static-entry'>;
}
declare module 'gatsby/cache-dir/emitter.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/emitter'>;
}
declare module 'gatsby/cache-dir/find-page.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/find-page'>;
}
declare module 'gatsby/cache-dir/history.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/history'>;
}
declare module 'gatsby/cache-dir/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/loader'>;
}
declare module 'gatsby/cache-dir/prefetcher.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/prefetcher'>;
}
declare module 'gatsby/cache-dir/production-app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/production-app'>;
}
declare module 'gatsby/cache-dir/register-service-worker.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/register-service-worker'>;
}
declare module 'gatsby/cache-dir/root.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/root'>;
}
declare module 'gatsby/cache-dir/shallow-differ.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/shallow-differ'>;
}
declare module 'gatsby/cache-dir/socketIo.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/socketIo'>;
}
declare module 'gatsby/cache-dir/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/static-entry'>;
}
declare module 'gatsby/cache-dir/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/strip-prefix'>;
}
declare module 'gatsby/dist/bin/gatsby.js' {
  declare module.exports: $Exports<'gatsby/dist/bin/gatsby'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/resolve-module-exports'>;
}
declare module 'gatsby/dist/bootstrap/get-config-file.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/get-config-file'>;
}
declare module 'gatsby/dist/bootstrap/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/index'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/index'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/load.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/load'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/validate.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/validate'>;
}
declare module 'gatsby/dist/bootstrap/log-line-function.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/log-line-function'>;
}
declare module 'gatsby/dist/bootstrap/page-hot-reloader.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/page-hot-reloader'>;
}
declare module 'gatsby/dist/bootstrap/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/resolve-module-exports'>;
}
declare module 'gatsby/dist/commands/build-css.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-css'>;
}
declare module 'gatsby/dist/commands/build-html.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-html'>;
}
declare module 'gatsby/dist/commands/build-javascript.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-javascript'>;
}
declare module 'gatsby/dist/commands/build.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build'>;
}
declare module 'gatsby/dist/commands/data-explorer.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/data-explorer'>;
}
declare module 'gatsby/dist/commands/develop-html.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop-html'>;
}
declare module 'gatsby/dist/commands/develop.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop'>;
}
declare module 'gatsby/dist/commands/serve.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/serve'>;
}
declare module 'gatsby/dist/internal-plugins/component-layout-creator/create-path.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-layout-creator/create-path',
  >;
}
declare module 'gatsby/dist/internal-plugins/component-layout-creator/gatsby-node.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-layout-creator/gatsby-node',
  >;
}
declare module 'gatsby/dist/internal-plugins/component-layout-creator/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/component-layout-creator/index'>;
}
declare module 'gatsby/dist/internal-plugins/component-layout-creator/validate-path.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-layout-creator/validate-path',
  >;
}
declare module 'gatsby/dist/internal-plugins/component-page-creator/create-path.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-page-creator/create-path',
  >;
}
declare module 'gatsby/dist/internal-plugins/component-page-creator/gatsby-node.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-page-creator/gatsby-node',
  >;
}
declare module 'gatsby/dist/internal-plugins/component-page-creator/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/component-page-creator/index'>;
}
declare module 'gatsby/dist/internal-plugins/component-page-creator/validate-path.js' {
  declare module.exports: $Exports<
    'gatsby/dist/internal-plugins/component-page-creator/validate-path',
  >;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/index'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge/index'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404/index'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/file-parser.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/file-parser'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/graphql-errors.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/graphql-errors'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/index'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/page-query-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/page-query-runner'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/pages-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/pages-writer'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-compiler.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-compiler'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-queue.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-queue'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-runner'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/query-watcher.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/query-watcher'>;
}
declare module 'gatsby/dist/internal-plugins/query-runner/redirects-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/query-runner/redirects-writer'>;
}
declare module 'gatsby/dist/joi-schemas/joi.js' {
  declare module.exports: $Exports<'gatsby/dist/joi-schemas/joi'>;
}
declare module 'gatsby/dist/redux/actions.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions'>;
}
declare module 'gatsby/dist/redux/actions/add-page-dependency.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/add-page-dependency'>;
}
declare module 'gatsby/dist/redux/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/index'>;
}
declare module 'gatsby/dist/redux/plugin-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/plugin-runner'>;
}
declare module 'gatsby/dist/redux/reducers/api-to-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/api-to-plugins'>;
}
declare module 'gatsby/dist/redux/reducers/component-data-dependencies.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/component-data-dependencies'>;
}
declare module 'gatsby/dist/redux/reducers/components.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/components'>;
}
declare module 'gatsby/dist/redux/reducers/config.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/config'>;
}
declare module 'gatsby/dist/redux/reducers/flattened-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/flattened-plugins'>;
}
declare module 'gatsby/dist/redux/reducers/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/index'>;
}
declare module 'gatsby/dist/redux/reducers/jobs.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/jobs'>;
}
declare module 'gatsby/dist/redux/reducers/last-action.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/last-action'>;
}
declare module 'gatsby/dist/redux/reducers/layouts.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/layouts'>;
}
declare module 'gatsby/dist/redux/reducers/nodes-touched.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes-touched'>;
}
declare module 'gatsby/dist/redux/reducers/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes'>;
}
declare module 'gatsby/dist/redux/reducers/pages.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/pages'>;
}
declare module 'gatsby/dist/redux/reducers/plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/plugins'>;
}
declare module 'gatsby/dist/redux/reducers/program.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/program'>;
}
declare module 'gatsby/dist/redux/reducers/redirects.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/redirects'>;
}
declare module 'gatsby/dist/redux/reducers/schema.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/schema'>;
}
declare module 'gatsby/dist/redux/reducers/status.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/status'>;
}
declare module 'gatsby/dist/schema/build-connection-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-connection-fields'>;
}
declare module 'gatsby/dist/schema/build-node-connections.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-node-connections'>;
}
declare module 'gatsby/dist/schema/build-node-types.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/build-node-types'>;
}
declare module 'gatsby/dist/schema/create-key.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-key'>;
}
declare module 'gatsby/dist/schema/create-sort-field.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-sort-field'>;
}
declare module 'gatsby/dist/schema/create-type-name.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/create-type-name'>;
}
declare module 'gatsby/dist/schema/data-tree-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/data-tree-utils'>;
}
declare module 'gatsby/dist/schema/index.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/index'>;
}
declare module 'gatsby/dist/schema/infer-graphql-input-fields-from-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-input-fields-from-fields'>;
}
declare module 'gatsby/dist/schema/infer-graphql-input-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-input-fields'>;
}
declare module 'gatsby/dist/schema/infer-graphql-type.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer-graphql-type'>;
}
declare module 'gatsby/dist/schema/node-interface.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node-interface'>;
}
declare module 'gatsby/dist/schema/node-tracking.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node-tracking'>;
}
declare module 'gatsby/dist/schema/node.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node'>;
}
declare module 'gatsby/dist/schema/prepare-regex.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/prepare-regex'>;
}
declare module 'gatsby/dist/schema/run-sift.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/run-sift'>;
}
declare module 'gatsby/dist/schema/types/type-date.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-date'>;
}
declare module 'gatsby/dist/schema/types/type-file.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-file'>;
}
declare module 'gatsby/dist/utils/api-browser-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-browser-docs'>;
}
declare module 'gatsby/dist/utils/api-node-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-node-docs'>;
}
declare module 'gatsby/dist/utils/api-runner-node.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-runner-node'>;
}
declare module 'gatsby/dist/utils/babel-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-config'>;
}
declare module 'gatsby/dist/utils/babel-plugin-extract-graphql.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-plugin-extract-graphql'>;
}
declare module 'gatsby/dist/utils/cache.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/cache'>;
}
declare module 'gatsby/dist/utils/checkpoints-promise.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/checkpoints-promise'>;
}
declare module 'gatsby/dist/utils/copy-static-directory.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/copy-static-directory'>;
}
declare module 'gatsby/dist/utils/create-node-id.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/create-node-id'>;
}
declare module 'gatsby/dist/utils/get-hash-fn.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-hash-fn'>;
}
declare module 'gatsby/dist/utils/get-ssl-cert.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-ssl-cert'>;
}
declare module 'gatsby/dist/utils/hashed-chunk-ids-plugin.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/hashed-chunk-ids-plugin'>;
}
declare module 'gatsby/dist/utils/js-chunk-names.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/js-chunk-names'>;
}
declare module 'gatsby/dist/utils/path.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/path'>;
}
declare module 'gatsby/dist/utils/source-nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/source-nodes'>;
}
declare module 'gatsby/dist/utils/test-require-error.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/test-require-error'>;
}
declare module 'gatsby/dist/utils/webpack-modify-validate.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-modify-validate'>;
}
declare module 'gatsby/dist/utils/webpack.config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack.config'>;
}
