// flow-typed signature: cf8cbee4ae17a39ae15fa053d7d26e2e
// flow-typed version: <<STUB>>/normalize.css_v^8.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
