// flow-typed signature: 4ffa33c20a44a992b3bf033a3566a49c
// flow-typed version: <<STUB>>/react-instantsearch_v^5.0.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-instantsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-instantsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-instantsearch/connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/native' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Configure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/createClassNames' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Highlighter' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Link' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/LinkList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/List' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/PanelCallbackHandler' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Select' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/components/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectAutoComplete' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectBreadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectConfigure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectCurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectHierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectHighlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectHitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectInfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectNumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectPagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectPoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectRange' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectRefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectSearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectSortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectStateResults' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectStats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/connectors/connectToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createConnector' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createIndex' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createInstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createInstantSearchManager' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createInstantSearchServer' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createStore' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/createWidgetsManager' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/findResultsState' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/highlightTags' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/Index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/indexUtils' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/InstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/propTypes' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/translatable' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/core/utils' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Configure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/RangeSlider' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/src/widgets/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/native' {
  declare module.exports: any;
}

declare module 'react-instantsearch/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Configure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/createClassNames' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Highlighter' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Link' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/LinkList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/List' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/PanelCallbackHandler' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Select' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/components/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectAutoComplete' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectBreadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectConfigure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectCurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectHierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectHighlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectHitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectInfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectNumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectPagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectPoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectRange' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectRefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectSearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectSortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectStateResults' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectStats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/connectors/connectToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createConnector' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createIndex' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createInstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createInstantSearchManager' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createInstantSearchServer' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createStore' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/createWidgetsManager' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/findResultsState' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/highlightTags' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/Index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/indexUtils' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/InstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/propTypes' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/translatable' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/core/utils' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Configure' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/RangeSlider' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch/src/widgets/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Connectors.min' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Core' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Core.min' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Dom.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-instantsearch/connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/connectors'>;
}
declare module 'react-instantsearch/dom.js' {
  declare module.exports: $Exports<'react-instantsearch/dom'>;
}
declare module 'react-instantsearch/es/connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/es/connectors'>;
}
declare module 'react-instantsearch/es/dom.js' {
  declare module.exports: $Exports<'react-instantsearch/es/dom'>;
}
declare module 'react-instantsearch/es/index.js' {
  declare module.exports: $Exports<'react-instantsearch/es/index'>;
}
declare module 'react-instantsearch/es/native.js' {
  declare module.exports: $Exports<'react-instantsearch/es/native'>;
}
declare module 'react-instantsearch/es/server.js' {
  declare module.exports: $Exports<'react-instantsearch/es/server'>;
}
declare module 'react-instantsearch/es/src/components/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Breadcrumb'>;
}
declare module 'react-instantsearch/es/src/components/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/ClearRefinements'>;
}
declare module 'react-instantsearch/es/src/components/Configure.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Configure'>;
}
declare module 'react-instantsearch/es/src/components/createClassNames.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/createClassNames'>;
}
declare module 'react-instantsearch/es/src/components/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/CurrentRefinements'>;
}
declare module 'react-instantsearch/es/src/components/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/HierarchicalMenu'>;
}
declare module 'react-instantsearch/es/src/components/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Highlight'>;
}
declare module 'react-instantsearch/es/src/components/Highlighter.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Highlighter'>;
}
declare module 'react-instantsearch/es/src/components/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Hits'>;
}
declare module 'react-instantsearch/es/src/components/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/HitsPerPage'>;
}
declare module 'react-instantsearch/es/src/components/index.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/index'>;
}
declare module 'react-instantsearch/es/src/components/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/InfiniteHits'>;
}
declare module 'react-instantsearch/es/src/components/Link.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Link'>;
}
declare module 'react-instantsearch/es/src/components/LinkList.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/LinkList'>;
}
declare module 'react-instantsearch/es/src/components/List.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/List'>;
}
declare module 'react-instantsearch/es/src/components/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Menu'>;
}
declare module 'react-instantsearch/es/src/components/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/MenuSelect'>;
}
declare module 'react-instantsearch/es/src/components/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/NumericMenu'>;
}
declare module 'react-instantsearch/es/src/components/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Pagination'>;
}
declare module 'react-instantsearch/es/src/components/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Panel'>;
}
declare module 'react-instantsearch/es/src/components/PanelCallbackHandler.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/PanelCallbackHandler'>;
}
declare module 'react-instantsearch/es/src/components/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/PoweredBy'>;
}
declare module 'react-instantsearch/es/src/components/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/RangeInput'>;
}
declare module 'react-instantsearch/es/src/components/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/RatingMenu'>;
}
declare module 'react-instantsearch/es/src/components/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/RefinementList'>;
}
declare module 'react-instantsearch/es/src/components/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/ScrollTo'>;
}
declare module 'react-instantsearch/es/src/components/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/SearchBox'>;
}
declare module 'react-instantsearch/es/src/components/Select.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Select'>;
}
declare module 'react-instantsearch/es/src/components/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Snippet'>;
}
declare module 'react-instantsearch/es/src/components/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/SortBy'>;
}
declare module 'react-instantsearch/es/src/components/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/Stats'>;
}
declare module 'react-instantsearch/es/src/components/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/components/ToggleRefinement'>;
}
declare module 'react-instantsearch/es/src/connectors/connectAutoComplete.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectAutoComplete'>;
}
declare module 'react-instantsearch/es/src/connectors/connectBreadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectBreadcrumb'>;
}
declare module 'react-instantsearch/es/src/connectors/connectConfigure.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectConfigure'>;
}
declare module 'react-instantsearch/es/src/connectors/connectCurrentRefinements.js' {
  declare module.exports: $Exports<
    'react-instantsearch/es/src/connectors/connectCurrentRefinements',
  >;
}
declare module 'react-instantsearch/es/src/connectors/connectHierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectHierarchicalMenu'>;
}
declare module 'react-instantsearch/es/src/connectors/connectHighlight.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectHighlight'>;
}
declare module 'react-instantsearch/es/src/connectors/connectHits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectHits'>;
}
declare module 'react-instantsearch/es/src/connectors/connectHitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectHitsPerPage'>;
}
declare module 'react-instantsearch/es/src/connectors/connectInfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectInfiniteHits'>;
}
declare module 'react-instantsearch/es/src/connectors/connectMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectMenu'>;
}
declare module 'react-instantsearch/es/src/connectors/connectNumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectNumericMenu'>;
}
declare module 'react-instantsearch/es/src/connectors/connectPagination.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectPagination'>;
}
declare module 'react-instantsearch/es/src/connectors/connectPoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectPoweredBy'>;
}
declare module 'react-instantsearch/es/src/connectors/connectRange.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectRange'>;
}
declare module 'react-instantsearch/es/src/connectors/connectRefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectRefinementList'>;
}
declare module 'react-instantsearch/es/src/connectors/connectScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectScrollTo'>;
}
declare module 'react-instantsearch/es/src/connectors/connectSearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectSearchBox'>;
}
declare module 'react-instantsearch/es/src/connectors/connectSortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectSortBy'>;
}
declare module 'react-instantsearch/es/src/connectors/connectStateResults.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectStateResults'>;
}
declare module 'react-instantsearch/es/src/connectors/connectStats.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectStats'>;
}
declare module 'react-instantsearch/es/src/connectors/connectToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/connectors/connectToggleRefinement'>;
}
declare module 'react-instantsearch/es/src/core/createConnector.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createConnector'>;
}
declare module 'react-instantsearch/es/src/core/createIndex.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createIndex'>;
}
declare module 'react-instantsearch/es/src/core/createInstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createInstantSearch'>;
}
declare module 'react-instantsearch/es/src/core/createInstantSearchManager.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createInstantSearchManager'>;
}
declare module 'react-instantsearch/es/src/core/createInstantSearchServer.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createInstantSearchServer'>;
}
declare module 'react-instantsearch/es/src/core/createStore.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createStore'>;
}
declare module 'react-instantsearch/es/src/core/createWidgetsManager.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/createWidgetsManager'>;
}
declare module 'react-instantsearch/es/src/core/findResultsState.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/findResultsState'>;
}
declare module 'react-instantsearch/es/src/core/highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/highlight'>;
}
declare module 'react-instantsearch/es/src/core/highlightTags.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/highlightTags'>;
}
declare module 'react-instantsearch/es/src/core/Index.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/Index'>;
}
declare module 'react-instantsearch/es/src/core/indexUtils.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/indexUtils'>;
}
declare module 'react-instantsearch/es/src/core/InstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/InstantSearch'>;
}
declare module 'react-instantsearch/es/src/core/propTypes.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/propTypes'>;
}
declare module 'react-instantsearch/es/src/core/translatable.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/translatable'>;
}
declare module 'react-instantsearch/es/src/core/utils.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/core/utils'>;
}
declare module 'react-instantsearch/es/src/widgets/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Breadcrumb'>;
}
declare module 'react-instantsearch/es/src/widgets/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/ClearRefinements'>;
}
declare module 'react-instantsearch/es/src/widgets/Configure.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Configure'>;
}
declare module 'react-instantsearch/es/src/widgets/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/CurrentRefinements'>;
}
declare module 'react-instantsearch/es/src/widgets/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/HierarchicalMenu'>;
}
declare module 'react-instantsearch/es/src/widgets/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Highlight'>;
}
declare module 'react-instantsearch/es/src/widgets/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Hits'>;
}
declare module 'react-instantsearch/es/src/widgets/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/HitsPerPage'>;
}
declare module 'react-instantsearch/es/src/widgets/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/InfiniteHits'>;
}
declare module 'react-instantsearch/es/src/widgets/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Menu'>;
}
declare module 'react-instantsearch/es/src/widgets/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/MenuSelect'>;
}
declare module 'react-instantsearch/es/src/widgets/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/NumericMenu'>;
}
declare module 'react-instantsearch/es/src/widgets/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Pagination'>;
}
declare module 'react-instantsearch/es/src/widgets/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Panel'>;
}
declare module 'react-instantsearch/es/src/widgets/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/PoweredBy'>;
}
declare module 'react-instantsearch/es/src/widgets/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/RangeInput'>;
}
declare module 'react-instantsearch/es/src/widgets/RangeSlider.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/RangeSlider'>;
}
declare module 'react-instantsearch/es/src/widgets/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/RatingMenu'>;
}
declare module 'react-instantsearch/es/src/widgets/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/RefinementList'>;
}
declare module 'react-instantsearch/es/src/widgets/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/ScrollTo'>;
}
declare module 'react-instantsearch/es/src/widgets/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/SearchBox'>;
}
declare module 'react-instantsearch/es/src/widgets/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Snippet'>;
}
declare module 'react-instantsearch/es/src/widgets/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/SortBy'>;
}
declare module 'react-instantsearch/es/src/widgets/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/Stats'>;
}
declare module 'react-instantsearch/es/src/widgets/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/es/src/widgets/ToggleRefinement'>;
}
declare module 'react-instantsearch/index' {
  declare module.exports: $Exports<'react-instantsearch'>;
}
declare module 'react-instantsearch/index.js' {
  declare module.exports: $Exports<'react-instantsearch'>;
}
declare module 'react-instantsearch/native.js' {
  declare module.exports: $Exports<'react-instantsearch/native'>;
}
declare module 'react-instantsearch/server.js' {
  declare module.exports: $Exports<'react-instantsearch/server'>;
}
declare module 'react-instantsearch/src/components/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Breadcrumb'>;
}
declare module 'react-instantsearch/src/components/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/ClearRefinements'>;
}
declare module 'react-instantsearch/src/components/Configure.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Configure'>;
}
declare module 'react-instantsearch/src/components/createClassNames.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/createClassNames'>;
}
declare module 'react-instantsearch/src/components/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/CurrentRefinements'>;
}
declare module 'react-instantsearch/src/components/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/HierarchicalMenu'>;
}
declare module 'react-instantsearch/src/components/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Highlight'>;
}
declare module 'react-instantsearch/src/components/Highlighter.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Highlighter'>;
}
declare module 'react-instantsearch/src/components/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Hits'>;
}
declare module 'react-instantsearch/src/components/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/HitsPerPage'>;
}
declare module 'react-instantsearch/src/components/index.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/index'>;
}
declare module 'react-instantsearch/src/components/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/InfiniteHits'>;
}
declare module 'react-instantsearch/src/components/Link.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Link'>;
}
declare module 'react-instantsearch/src/components/LinkList.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/LinkList'>;
}
declare module 'react-instantsearch/src/components/List.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/List'>;
}
declare module 'react-instantsearch/src/components/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Menu'>;
}
declare module 'react-instantsearch/src/components/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/MenuSelect'>;
}
declare module 'react-instantsearch/src/components/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/NumericMenu'>;
}
declare module 'react-instantsearch/src/components/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Pagination'>;
}
declare module 'react-instantsearch/src/components/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Panel'>;
}
declare module 'react-instantsearch/src/components/PanelCallbackHandler.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/PanelCallbackHandler'>;
}
declare module 'react-instantsearch/src/components/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/PoweredBy'>;
}
declare module 'react-instantsearch/src/components/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/RangeInput'>;
}
declare module 'react-instantsearch/src/components/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/RatingMenu'>;
}
declare module 'react-instantsearch/src/components/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/RefinementList'>;
}
declare module 'react-instantsearch/src/components/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/ScrollTo'>;
}
declare module 'react-instantsearch/src/components/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/SearchBox'>;
}
declare module 'react-instantsearch/src/components/Select.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Select'>;
}
declare module 'react-instantsearch/src/components/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Snippet'>;
}
declare module 'react-instantsearch/src/components/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/SortBy'>;
}
declare module 'react-instantsearch/src/components/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/Stats'>;
}
declare module 'react-instantsearch/src/components/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/src/components/ToggleRefinement'>;
}
declare module 'react-instantsearch/src/connectors/connectAutoComplete.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectAutoComplete'>;
}
declare module 'react-instantsearch/src/connectors/connectBreadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectBreadcrumb'>;
}
declare module 'react-instantsearch/src/connectors/connectConfigure.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectConfigure'>;
}
declare module 'react-instantsearch/src/connectors/connectCurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectCurrentRefinements'>;
}
declare module 'react-instantsearch/src/connectors/connectHierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectHierarchicalMenu'>;
}
declare module 'react-instantsearch/src/connectors/connectHighlight.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectHighlight'>;
}
declare module 'react-instantsearch/src/connectors/connectHits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectHits'>;
}
declare module 'react-instantsearch/src/connectors/connectHitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectHitsPerPage'>;
}
declare module 'react-instantsearch/src/connectors/connectInfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectInfiniteHits'>;
}
declare module 'react-instantsearch/src/connectors/connectMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectMenu'>;
}
declare module 'react-instantsearch/src/connectors/connectNumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectNumericMenu'>;
}
declare module 'react-instantsearch/src/connectors/connectPagination.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectPagination'>;
}
declare module 'react-instantsearch/src/connectors/connectPoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectPoweredBy'>;
}
declare module 'react-instantsearch/src/connectors/connectRange.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectRange'>;
}
declare module 'react-instantsearch/src/connectors/connectRefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectRefinementList'>;
}
declare module 'react-instantsearch/src/connectors/connectScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectScrollTo'>;
}
declare module 'react-instantsearch/src/connectors/connectSearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectSearchBox'>;
}
declare module 'react-instantsearch/src/connectors/connectSortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectSortBy'>;
}
declare module 'react-instantsearch/src/connectors/connectStateResults.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectStateResults'>;
}
declare module 'react-instantsearch/src/connectors/connectStats.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectStats'>;
}
declare module 'react-instantsearch/src/connectors/connectToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/src/connectors/connectToggleRefinement'>;
}
declare module 'react-instantsearch/src/core/createConnector.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createConnector'>;
}
declare module 'react-instantsearch/src/core/createIndex.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createIndex'>;
}
declare module 'react-instantsearch/src/core/createInstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createInstantSearch'>;
}
declare module 'react-instantsearch/src/core/createInstantSearchManager.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createInstantSearchManager'>;
}
declare module 'react-instantsearch/src/core/createInstantSearchServer.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createInstantSearchServer'>;
}
declare module 'react-instantsearch/src/core/createStore.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createStore'>;
}
declare module 'react-instantsearch/src/core/createWidgetsManager.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/createWidgetsManager'>;
}
declare module 'react-instantsearch/src/core/findResultsState.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/findResultsState'>;
}
declare module 'react-instantsearch/src/core/highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/highlight'>;
}
declare module 'react-instantsearch/src/core/highlightTags.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/highlightTags'>;
}
declare module 'react-instantsearch/src/core/Index.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/Index'>;
}
declare module 'react-instantsearch/src/core/indexUtils.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/indexUtils'>;
}
declare module 'react-instantsearch/src/core/InstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/InstantSearch'>;
}
declare module 'react-instantsearch/src/core/propTypes.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/propTypes'>;
}
declare module 'react-instantsearch/src/core/translatable.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/translatable'>;
}
declare module 'react-instantsearch/src/core/utils.js' {
  declare module.exports: $Exports<'react-instantsearch/src/core/utils'>;
}
declare module 'react-instantsearch/src/widgets/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Breadcrumb'>;
}
declare module 'react-instantsearch/src/widgets/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/ClearRefinements'>;
}
declare module 'react-instantsearch/src/widgets/Configure.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Configure'>;
}
declare module 'react-instantsearch/src/widgets/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/CurrentRefinements'>;
}
declare module 'react-instantsearch/src/widgets/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/HierarchicalMenu'>;
}
declare module 'react-instantsearch/src/widgets/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Highlight'>;
}
declare module 'react-instantsearch/src/widgets/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Hits'>;
}
declare module 'react-instantsearch/src/widgets/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/HitsPerPage'>;
}
declare module 'react-instantsearch/src/widgets/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/InfiniteHits'>;
}
declare module 'react-instantsearch/src/widgets/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Menu'>;
}
declare module 'react-instantsearch/src/widgets/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/MenuSelect'>;
}
declare module 'react-instantsearch/src/widgets/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/NumericMenu'>;
}
declare module 'react-instantsearch/src/widgets/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Pagination'>;
}
declare module 'react-instantsearch/src/widgets/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Panel'>;
}
declare module 'react-instantsearch/src/widgets/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/PoweredBy'>;
}
declare module 'react-instantsearch/src/widgets/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/RangeInput'>;
}
declare module 'react-instantsearch/src/widgets/RangeSlider.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/RangeSlider'>;
}
declare module 'react-instantsearch/src/widgets/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/RatingMenu'>;
}
declare module 'react-instantsearch/src/widgets/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/RefinementList'>;
}
declare module 'react-instantsearch/src/widgets/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/ScrollTo'>;
}
declare module 'react-instantsearch/src/widgets/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/SearchBox'>;
}
declare module 'react-instantsearch/src/widgets/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Snippet'>;
}
declare module 'react-instantsearch/src/widgets/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/SortBy'>;
}
declare module 'react-instantsearch/src/widgets/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/Stats'>;
}
declare module 'react-instantsearch/src/widgets/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch/src/widgets/ToggleRefinement'>;
}
declare module 'react-instantsearch/umd/Connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Connectors'>;
}
declare module 'react-instantsearch/umd/Connectors.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Connectors.min'>;
}
declare module 'react-instantsearch/umd/Core.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Core'>;
}
declare module 'react-instantsearch/umd/Core.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Core.min'>;
}
declare module 'react-instantsearch/umd/Dom.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Dom'>;
}
declare module 'react-instantsearch/umd/Dom.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Dom.min'>;
}
