// flow-typed signature: ae0abce0c97a08a19e3eeb161d54c8cb
// flow-typed version: <<STUB>>/remark-preset-lint-recommended_v^3.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-recommended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-recommended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'remark-preset-lint-recommended/index' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
declare module 'remark-preset-lint-recommended/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
