// flow-typed signature: 423cc504f23857878f2771c3c4e36c49
// flow-typed version: <<STUB>>/stylelint-config-sass-guidelines_v^5.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-sass-guidelines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-sass-guidelines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'stylelint-config-sass-guidelines/index' {
  declare module.exports: $Exports<'stylelint-config-sass-guidelines'>;
}
declare module 'stylelint-config-sass-guidelines/index.js' {
  declare module.exports: $Exports<'stylelint-config-sass-guidelines'>;
}
